# This is a basic example of a Worky config file.
# This config id for a project that has a core and a ui component.
# The "core" is loaded in the "charm" IDE and the "ui" is loaded in the "webstorm" IDE.

# The variables can be used in all the config file except for the steps name.
# The value of the variables used in the step name define the command that will be executed.
[variables]
core = "charm"
ui = "webstorm"

# Your variables can use environment variables as well.
# The environment variables are resolved only when the command is executed.
base_project_dir = "$HOME/project_dir"

# You can use a variable to define another variable.
# This helps readability and avoid the steps with the same name that are not allowed in TOML syntax.
core_project_dir = "${base_project_dir}/core_dir"
ui_project_dir = "${base_project_dir}/ui_dir"


# Define the steps to be executed.
# The steps are executed in the same order they are defined.

# This step named "core" run the charm IDE and load the ${core_project_dir} using the variable defined above: core = "charm"
[core]
# args is a list of arguments that are passed to the command.
# The command that run from this step is:
#   core "${base_project_dir}/core_dir"
# This command is executed expanding the variables as the following:
#  charm "$HOME/project_dir/core_dir"
args = [
    "${core_project_dir}"
]

[ui]
args = [
    "${ui_project_dir}"
]